/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceUsuario;

    //<editor-fold defaultstate="collapsed" desc="Imports">
import dominio.*;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
//</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="autor">
/**
 *
 * @author whoami
 */
//</editor-fold>
public class FrameCarroNovo extends javax.swing.JPanel {

    //<editor-fold defaultstate="collapsed" desc="Atributos">
    private ListaDeAutomoveis listaAutomoveis;
    CarroNovo carro;
    private int excluira;
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Construtor do frame">
    /**
     * Creates new form FrameInicial
     */
    public FrameCarroNovo() {

        initComponents();

        DefaultListModel listModel = new DefaultListModel();

        listaAutomoveis = new ListaDeAutomoveis("CarroNovo");

        listaAutomoveis.lerArquivo();

        editar.setEnabled(false);
        excluir.setEnabled(false);
        visualizar.setEnabled(false);

        for (Marca marca : Marca.values()) {
            jComboBoxMarcaCadastrar.addItem(marca);
            jComboBoxMarcaCadastrar1.addItem(marca);
        }

        for (Cambio cambio : Cambio.values()) {
            jComboBoxCambioCadastrar.addItem(cambio);
            jComboBoxCambioCadastrar1.addItem(cambio);
        }

    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Generated code">
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        JTabbedPaneCarroNovo = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        cadastrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListAutomovel = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        visualizar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxMarcaCadastrar = new javax.swing.JComboBox();
        jTextFieldModeloCadastrar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPassageirosCadastrar = new javax.swing.JTextField();
        jTextFieldAnoCadastrar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldValorCadastrar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldAroCadastrar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxCambioCadastrar = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCorCadastrar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldPortasCadastrar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldMediaKmCadastrar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaOpcionaisCadastrar = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldPotenciaDoMotorCadastrar = new javax.swing.JTextField();
        jButtonSalvarCadastrar = new javax.swing.JButton();
        jButtonVoltarCadastrar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jComboBoxMarcaCadastrar1 = new javax.swing.JComboBox();
        jTextFieldAnoCadastrar1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldModeloCadastrar1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jComboBoxCambioCadastrar1 = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldAroCadastrar1 = new javax.swing.JTextField();
        jTextFieldPortasCadastrar1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldValorCadastrar1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldCorCadastrar1 = new javax.swing.JTextField();
        jTextFieldPassageirosCadastrar1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldPotenciaDoMotorCadastrar1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldMediaKmCadastrar1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaOpcionaisCadastrar1 = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jButtonSalvarEditar = new javax.swing.JButton();
        jButtonVoltarCadastrar1 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jTextFieldAnoCadastrar2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextFieldModeloCadastrar2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldAroCadastrar2 = new javax.swing.JTextField();
        jTextFieldPortasCadastrar2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextFieldValorCadastrar2 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextFieldCorCadastrar2 = new javax.swing.JTextField();
        jTextFieldPassageirosCadastrar2 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jTextFieldPotenciaDoMotorCadastrar2 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jTextFieldMediaKmCadastrar2 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaOpcionaisCadastrar2 = new javax.swing.JTextArea();
        jLabel36 = new javax.swing.JLabel();
        jButtonVoltarCadastrar2 = new javax.swing.JButton();
        jTextFieldCambioCadastrar2 = new javax.swing.JTextField();
        jTextFieldMarcaCadastrar2 = new javax.swing.JTextField();

        jButton10.setText("jButton10");

        jButton11.setText("jButton11");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel2.setText("jLabel2");

        jLabel37.setText("jLabel37");

        cadastrar.setText("Cadastrar carro");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        jListAutomovel.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListAutomovelValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListAutomovel);

        jButton2.setText("Listar tudo");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Marca", "Ano", "Cor", "Valor", "Codigo" }));

        jLabel1.setText("Buscar por:");

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        visualizar.setText("Visualizar mais");
        visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarActionPerformed(evt);
            }
        });

        jButton5.setText("Limpar busca");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        excluir.setText("Excluir");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(visualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluir))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(visualizar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        JTabbedPaneCarroNovo.addTab("Pesquisar", jPanel1);

        jLabel3.setText("Marca:");

        jLabel4.setText("Modelo:");

        jComboBoxMarcaCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMarcaCadastrarActionPerformed(evt);
            }
        });

        jLabel5.setText("Ano:");

        jLabel6.setText("Passageiros:");

        jLabel7.setText("Valor:");

        jLabel8.setText("Portas:");

        jLabel9.setText("Cambio:");

        jLabel10.setText("Cor:");

        jLabel11.setText("Aro:");

        jLabel12.setText("Media km:");

        jLabel13.setText("Opcionais:");

        jTextAreaOpcionaisCadastrar.setColumns(20);
        jTextAreaOpcionaisCadastrar.setRows(5);
        jScrollPane2.setViewportView(jTextAreaOpcionaisCadastrar);

        jLabel14.setText("Potencia do motor:");

        jButtonSalvarCadastrar.setText("Salvar");
        jButtonSalvarCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarCadastrarActionPerformed(evt);
            }
        });

        jButtonVoltarCadastrar.setText("Voltar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSalvarCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonVoltarCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3)
                            .addComponent(jLabel14)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldPotenciaDoMotorCadastrar, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCorCadastrar, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldValorCadastrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(jComboBoxCambioCadastrar, javax.swing.GroupLayout.Alignment.LEADING, 0, 166, Short.MAX_VALUE)
                                    .addComponent(jComboBoxMarcaCadastrar, javax.swing.GroupLayout.Alignment.LEADING, 0, 166, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextFieldMediaKmCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldPassageirosCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldPortasCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addComponent(jLabel5)
                                        .addGap(7, 7, 7)
                                        .addComponent(jTextFieldAnoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldAroCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldModeloCadastrar)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)))))
                .addGap(0, 222, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldAnoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMarcaCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldModeloCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCambioCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldAroCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldValorCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldPortasCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCorCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldPassageirosCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPotenciaDoMotorCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldMediaKmCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalvarCadastrar)
                    .addComponent(jButtonVoltarCadastrar))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        JTabbedPaneCarroNovo.addTab("Cadastrar", jPanel2);

        jLabel15.setText("Marca:");

        jComboBoxMarcaCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMarcaCadastrar1ActionPerformed(evt);
            }
        });

        jLabel16.setText("Ano:");

        jLabel17.setText("Modelo:");

        jLabel18.setText("Cambio:");

        jLabel19.setText("Aro:");

        jLabel20.setText("Portas:");

        jLabel21.setText("Valor:");

        jLabel22.setText("Cor:");

        jLabel23.setText("Potencia do motor:");

        jLabel24.setText("Media km:");

        jTextAreaOpcionaisCadastrar1.setColumns(20);
        jTextAreaOpcionaisCadastrar1.setRows(5);
        jScrollPane3.setViewportView(jTextAreaOpcionaisCadastrar1);

        jLabel25.setText("Opcionais:");

        jButtonSalvarEditar.setText("Salvar");
        jButtonSalvarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarEditarActionPerformed(evt);
            }
        });

        jButtonVoltarCadastrar1.setText("Voltar");

        jLabel38.setText("Passageiros:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel22)
                    .addComponent(jLabel18)
                    .addComponent(jLabel15)
                    .addComponent(jLabel23)
                    .addComponent(jLabel21)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldPotenciaDoMotorCadastrar1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCorCadastrar1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldValorCadastrar1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxCambioCadastrar1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxMarcaCadastrar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMediaKmCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(129, 129, 129))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel38))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldPassageirosCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jTextFieldPortasCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextFieldAroCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldAnoCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jButtonSalvarEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonVoltarCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldModeloCadastrar1)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(98, 98, 98))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldAnoCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMarcaCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldModeloCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCambioCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldAroCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldValorCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jTextFieldPortasCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCorCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jTextFieldPassageirosCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPotenciaDoMotorCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jTextFieldMediaKmCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalvarEditar)
                    .addComponent(jButtonVoltarCadastrar1))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        JTabbedPaneCarroNovo.addTab("Editar", jPanel4);

        jLabel26.setText("Marca:");

        jLabel27.setText("Ano:");

        jLabel28.setText("Modelo:");

        jLabel29.setText("Cambio:");

        jLabel30.setText("Aro:");

        jTextFieldAroCadastrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAroCadastrar2ActionPerformed(evt);
            }
        });

        jLabel31.setText("Portas:");

        jLabel32.setText("Valor:");

        jLabel33.setText("Cor:");

        jLabel34.setText("Potencia do motor:");

        jLabel35.setText("Media km:");

        jTextAreaOpcionaisCadastrar2.setColumns(20);
        jTextAreaOpcionaisCadastrar2.setRows(5);
        jScrollPane4.setViewportView(jTextAreaOpcionaisCadastrar2);

        jLabel36.setText("Opcionais:");

        jButtonVoltarCadastrar2.setText("Voltar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel36)
                    .addComponent(jLabel33)
                    .addComponent(jLabel29)
                    .addComponent(jLabel26)
                    .addComponent(jLabel34)
                    .addComponent(jLabel32)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jTextFieldModeloCadastrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(240, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldPotenciaDoMotorCadastrar2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCorCadastrar2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldValorCadastrar2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCambioCadastrar2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldMarcaCadastrar2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(77, 77, 77)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAnoCadastrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel35)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldMediaKmCadastrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextFieldPassageirosCadastrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel31)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldPortasCadastrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel30)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldAroCadastrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonVoltarCadastrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jTextFieldAnoCadastrar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMarcaCadastrar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTextFieldModeloCadastrar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jTextFieldAroCadastrar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(jTextFieldCambioCadastrar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldValorCadastrar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(jTextFieldPortasCadastrar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCorCadastrar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(jTextFieldPassageirosCadastrar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPotenciaDoMotorCadastrar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(jTextFieldMediaKmCadastrar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVoltarCadastrar2)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        JTabbedPaneCarroNovo.addTab("Visualizar", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JTabbedPaneCarroNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTabbedPaneCarroNovo)
        );
    }// </editor-fold>//GEN-END:initComponents
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Botao excluir">
    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        DefaultListModel listModel = new DefaultListModel();
        excluira = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente excluir este automovel ?",
                "Excluir",
                JOptionPane.YES_NO_OPTION);
        if (excluira == JOptionPane.YES_OPTION) {
            listaAutomoveis.removeAutomovel(Integer.parseInt(
                    jListAutomovel.getSelectedValue().toString()));
            boolean boo = listaAutomoveis.escreverArquivo();
            if (boo) {
                System.out.println("excluido de boa!!! :)");
            }
            listModel.removeAllElements();
            listModel.clear();
            listarTudo();
        }
    }//GEN-LAST:event_excluirActionPerformed
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Sei la">
    private void jComboBoxMarcaCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMarcaCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMarcaCadastrarActionPerformed

    private void jComboBoxMarcaCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMarcaCadastrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMarcaCadastrar1ActionPerformed

    private void jTextFieldAroCadastrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAroCadastrar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAroCadastrar2ActionPerformed
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="main inutil">
    public static void main(String[] args) {
        FrameCarroNovo c = new FrameCarroNovo();
        c.setVisible(true);
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Botao cadastrar">
    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        JTabbedPaneCarroNovo.setSelectedIndex(1);
        JTabbedPaneCarroNovo.setEnabledAt(0, false);
        JTabbedPaneCarroNovo.setEnabledAt(1, true);
        JTabbedPaneCarroNovo.setEnabledAt(2, false);
        JTabbedPaneCarroNovo.setEnabledAt(3, false);
    }//GEN-LAST:event_cadastrarActionPerformed
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Botao editar">
    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed

        try {
            int buscar = Integer.parseInt(jListAutomovel.getSelectedValue().toString());
            Automovel auto = listaAutomoveis.consultarPorCodigo(buscar);
            carro = (CarroNovo) auto;

            JTabbedPaneCarroNovo.setSelectedIndex(2);
            JTabbedPaneCarroNovo.setEnabledAt(0, false);
            JTabbedPaneCarroNovo.setEnabledAt(1, false);
            JTabbedPaneCarroNovo.setEnabledAt(2, true);
            JTabbedPaneCarroNovo.setEnabledAt(3, false);

            jComboBoxMarcaCadastrar1.setSelectedItem(carro.getMarca().getMarca());
            jTextFieldAnoCadastrar1.setText(String.valueOf(carro.getAno()));
            jTextFieldModeloCadastrar1.setText(carro.getModelo());
            jComboBoxCambioCadastrar1.setSelectedItem(carro.getCambio().getCambio());
            jTextFieldAroCadastrar1.setText(String.valueOf(carro.getAro()));
            jTextFieldValorCadastrar1.setText(String.valueOf(carro.getValor()));
            jTextFieldPortasCadastrar1.setText(String.valueOf(carro.getQtdPortas()));
            jTextFieldCorCadastrar1.setText(carro.getCor());
            jTextFieldPassageirosCadastrar1.setText(String.valueOf(carro.getQtdPassageiros()));
            jTextFieldPotenciaDoMotorCadastrar1.setText(String.valueOf(carro.getPotenciaMotor()));
            jTextFieldMediaKmCadastrar1.setText(String.valueOf(carro.getMediaKmLitro()));
            jTextAreaOpcionaisCadastrar1.setText(carro.getOpcionais());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_editarActionPerformed
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Funcoes Listar">
    //<editor-fold defaultstate="collapsed" desc="Listar">
    /**
     * metodo listar um carro novo
     *
     * @param l
     */
    private void listar(Automovel l) {

        DefaultListModel listModel = new DefaultListModel();
        if (l != null) {

            listModel.addElement(l.getCodigo());
            jListAutomovel.setModel(listModel);
        } else {
            listModel.clear();
            jListAutomovel.setModel(listModel);
        }
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Listar varios">
    /**
     * metodo para listar varios automoveis
     *
     * @param lista
     * @return true caso consiga, false caso contrario
     */
    private boolean listarVarios(List<Automovel> lista) {
        DefaultListModel listModel = new DefaultListModel();
        jListAutomovel.removeAll();
        if (lista != null) {
            for (int i = 0; i < lista.size(); i++) {
                listModel.addElement(lista.get(i).getCodigo());
            }
            jListAutomovel.setModel(listModel);
        } else {
            listModel.clear();
            jListAutomovel.setModel(listModel);
            return false;
        }
        return true;
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Listar tudo">
    /**
     * listar varios carros novos
     */
    private void listarTudo() {

        DefaultListModel listModel = new DefaultListModel();

        for (Automovel l : listaAutomoveis.getListaDeAutomoveis()) {
            CarroNovo m = (CarroNovo) l;
            listModel.addElement(m.getCodigo());
            jListAutomovel.setModel(listModel);
            System.out.println(m.toString());
        }
    }
    //</editor-fold>

    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Buscar">
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        DefaultListModel listModel = new DefaultListModel();

        listModel.clear();

        if (jComboBox1.getSelectedItem().toString().equals("Marca")) {
            try {
                String buscar = jTextField1.getText();
                listarVarios(listaAutomoveis.consultarPorMarca(buscar));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
            }
        } else if (jComboBox1.getSelectedItem().toString().equals("Ano")) {
            try {
                int buscar = Integer.parseInt(jTextField1.getText());
                listarVarios(listaAutomoveis.consultarPorAno(buscar));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
            }
        } else if (jComboBox1.getSelectedItem().toString().equals("Cor")) {
            try {
                String buscar = jTextField1.getText();
                listarVarios(listaAutomoveis.consultarPorCor(buscar));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
            }
        } else if (jComboBox1.getSelectedItem().toString().equals("Valor")) {
            try {
                Double buscar = Double.parseDouble(jTextField1.getText());
                listarVarios(listaAutomoveis.consultarPorValor(buscar));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
            }
        } else if (jComboBox1.getSelectedItem().toString().equals("Codigo")) {
            try {
                int buscar = Integer.parseInt(jTextField1.getText());
                listar(listaAutomoveis.consultarPorCodigo(buscar));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Erro! ");
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Salvar cadastrar">
    private void jButtonSalvarCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarCadastrarActionPerformed
        int ano = 0, aro = 0, qtdPassageiros = 0, qtdPortas = 0;
        String cor, opcionais, modelo;
        double valor = 0, mediaKmLitro = 0, potenciaMotor = 0;
        Marca marca;
        Cambio cambio;

        try {

            ano = Integer.parseInt(jTextFieldAnoCadastrar.getText());
            aro = Integer.parseInt(jTextFieldAroCadastrar.getText());
            qtdPassageiros = Integer.parseInt(jTextFieldPassageirosCadastrar.getText());
            qtdPortas = Integer.parseInt(jTextFieldPortasCadastrar.getText());

            cor = jTextFieldCorCadastrar.getText();
            opcionais = jTextAreaOpcionaisCadastrar.getText();
            modelo = jTextFieldModeloCadastrar.getText();

            valor = Double.parseDouble(jTextFieldValorCadastrar.getText());
            mediaKmLitro = Double.parseDouble(jTextFieldMediaKmCadastrar.getText());
            potenciaMotor = Double.parseDouble(jTextFieldPotenciaDoMotorCadastrar.getText());

            marca = Marca.verificaMarca(jComboBoxMarcaCadastrar.getSelectedItem().toString());

            cambio = Cambio.verificaCambio(jComboBoxCambioCadastrar.getSelectedItem().toString());

            CarroNovo c = new CarroNovo(ano, aro, cor, marca, mediaKmLitro, modelo, opcionais, valor, qtdPortas, potenciaMotor, cambio, qtdPassageiros);

            try {
                listaAutomoveis.escreverArquivo();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
            }

        } catch (NumberFormatException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
        }

    }//GEN-LAST:event_jButtonSalvarCadastrarActionPerformed
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Salvar editar">
    private void jButtonSalvarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarEditarActionPerformed
        try {
            carro.setAno(Integer.parseInt(jTextFieldAnoCadastrar1.getText()));
            carro.setAro(Integer.parseInt(jTextFieldAroCadastrar1.getText()));
            carro.setCor(jTextFieldCorCadastrar1.getText());
            carro.setMarca(Marca.verificaMarca(jComboBoxCambioCadastrar1.getSelectedItem().toString()));
            carro.setMediaKmLitro(Double.parseDouble(jTextFieldMediaKmCadastrar1.getText()));
            carro.setModelo(jTextFieldModeloCadastrar1.getText());
            carro.setOpcionais(jTextAreaOpcionaisCadastrar1.getText());
            carro.setQtdPassageiros(Integer.parseInt(jTextFieldPassageirosCadastrar1.getText()));
            carro.setValor(Double.parseDouble(jTextFieldValorCadastrar1.getText()));
            carro.setQtdPortas(Integer.parseInt(jTextFieldPortasCadastrar1.getText()));
            carro.setPotenciaMotor(Double.parseDouble(jTextFieldPotenciaDoMotorCadastrar1.getText()));
            carro.setCambio(Cambio.verificaCambio(jComboBoxCambioCadastrar1.getSelectedItem().toString()));

            boolean boo = listaAutomoveis.escreverArquivo();

            if (boo) {
                JOptionPane.showMessageDialog(null, "Ecrito com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Erro!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonSalvarEditarActionPerformed
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="sei la">
    private void jListAutomovelValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListAutomovelValueChanged
        editar.setEnabled(true);
        excluir.setEnabled(true);
        visualizar.setEnabled(true);
    }//GEN-LAST:event_jListAutomovelValueChanged
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Visualizar mais">
    private void visualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarActionPerformed
        try {
            int buscar = Integer.parseInt(jListAutomovel.getSelectedValue().toString());
            Automovel auto = listaAutomoveis.consultarPorCodigo(buscar);
            carro = (CarroNovo) auto;

            JTabbedPaneCarroNovo.setSelectedIndex(2);
            JTabbedPaneCarroNovo.setEnabledAt(0, false);
            JTabbedPaneCarroNovo.setEnabledAt(1, false);
            JTabbedPaneCarroNovo.setEnabledAt(2, false);
            JTabbedPaneCarroNovo.setEnabledAt(3, true);

            jTextFieldMarcaCadastrar2.setText(String.valueOf(carro.getMarca().toString()));
            jTextFieldAnoCadastrar2.setText(String.valueOf(carro.getAno()));
            jTextFieldModeloCadastrar2.setText(carro.getModelo());
            jTextFieldCambioCadastrar2.setText(carro.getCambio().toString());
            jTextFieldAroCadastrar2.setText(String.valueOf(carro.getAro()));
            jTextFieldValorCadastrar2.setText(String.valueOf(carro.getValor()));
            jTextFieldPortasCadastrar2.setText(String.valueOf(carro.getQtdPortas()));
            jTextFieldCorCadastrar2.setText(carro.getCor());
            jTextFieldPassageirosCadastrar2.setText(String.valueOf(carro.getQtdPassageiros()));
            jTextFieldPotenciaDoMotorCadastrar2.setText(String.valueOf(carro.getPotenciaMotor()));
            jTextFieldMediaKmCadastrar2.setText(String.valueOf(carro.getMediaKmLitro()));
            jTextAreaOpcionaisCadastrar2.setText(carro.getOpcionais());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_visualizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        listarVarios(null);
    }//GEN-LAST:event_jButton5ActionPerformed
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Variables declaration">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane JTabbedPaneCarroNovo;
    private javax.swing.JButton cadastrar;
    private javax.swing.JButton editar;
    private javax.swing.JButton excluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonSalvarCadastrar;
    private javax.swing.JButton jButtonSalvarEditar;
    private javax.swing.JButton jButtonVoltarCadastrar;
    private javax.swing.JButton jButtonVoltarCadastrar1;
    private javax.swing.JButton jButtonVoltarCadastrar2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBoxCambioCadastrar;
    private javax.swing.JComboBox jComboBoxCambioCadastrar1;
    private javax.swing.JComboBox jComboBoxMarcaCadastrar;
    private javax.swing.JComboBox jComboBoxMarcaCadastrar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jListAutomovel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextAreaOpcionaisCadastrar;
    private javax.swing.JTextArea jTextAreaOpcionaisCadastrar1;
    private javax.swing.JTextArea jTextAreaOpcionaisCadastrar2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldAnoCadastrar;
    private javax.swing.JTextField jTextFieldAnoCadastrar1;
    private javax.swing.JTextField jTextFieldAnoCadastrar2;
    private javax.swing.JTextField jTextFieldAroCadastrar;
    private javax.swing.JTextField jTextFieldAroCadastrar1;
    private javax.swing.JTextField jTextFieldAroCadastrar2;
    private javax.swing.JTextField jTextFieldCambioCadastrar2;
    private javax.swing.JTextField jTextFieldCorCadastrar;
    private javax.swing.JTextField jTextFieldCorCadastrar1;
    private javax.swing.JTextField jTextFieldCorCadastrar2;
    private javax.swing.JTextField jTextFieldMarcaCadastrar2;
    private javax.swing.JTextField jTextFieldMediaKmCadastrar;
    private javax.swing.JTextField jTextFieldMediaKmCadastrar1;
    private javax.swing.JTextField jTextFieldMediaKmCadastrar2;
    private javax.swing.JTextField jTextFieldModeloCadastrar;
    private javax.swing.JTextField jTextFieldModeloCadastrar1;
    private javax.swing.JTextField jTextFieldModeloCadastrar2;
    private javax.swing.JTextField jTextFieldPassageirosCadastrar;
    private javax.swing.JTextField jTextFieldPassageirosCadastrar1;
    private javax.swing.JTextField jTextFieldPassageirosCadastrar2;
    private javax.swing.JTextField jTextFieldPortasCadastrar;
    private javax.swing.JTextField jTextFieldPortasCadastrar1;
    private javax.swing.JTextField jTextFieldPortasCadastrar2;
    private javax.swing.JTextField jTextFieldPotenciaDoMotorCadastrar;
    private javax.swing.JTextField jTextFieldPotenciaDoMotorCadastrar1;
    private javax.swing.JTextField jTextFieldPotenciaDoMotorCadastrar2;
    private javax.swing.JTextField jTextFieldValorCadastrar;
    private javax.swing.JTextField jTextFieldValorCadastrar1;
    private javax.swing.JTextField jTextFieldValorCadastrar2;
    private javax.swing.JButton visualizar;
    // End of variables declaration//GEN-END:variables
}
//</editor-fold>
